# version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3 # Image officielle avec Postgres + PostGIS
    container_name: find_your_job_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rahlofpgsql
      - POSTGRES_DB=fyj_database
    ports:
      - "5432:5432" # Relie le port du container à ton PC
    volumes:
      - postgres_data:/var/lib/postgresql/data # Garde tes données même si on éteint

volumes:
  postgres_data: